### PR TITLE
fix: default empty input_schema for Anthropic function tools with nil params

### LINKED ISSUE #1843: [Bug/错误]: 升级至最新版本后 anthropic 接口转 codex 接口报错
### Pre-submission Checklist / 提交前检查

- [x] I have searched the [existing issues](https://github.com/looplj/axonhub/issues) and this bug has not been reported / 我已搜索现有 issues，此 Bug 尚未被报告
- [x] I have read the [documentation](https://github.com/looplj/axonhub#readme) / 我已阅读文档
- [x] I am using the latest version of AxonHub / 我正在使用 AxonHub 的最新版本

### FAQ Check / FAQ 检查

- [x] I have checked the [FAQ](https://github.com/looplj/axonhub/issues/1374) and this bug is not covered there / 我已查阅 FAQ，此 Bug 未被覆盖

### Bug Description / Bug 描述

渠道格式为 Anthropic message，客户端为 codex，所有请求均报 422 错误：

failed to stream request: Request failed: Unprocessable Entity, error: {"detail":[{"type":"missing","loc":["body","tools",10,"input_schema"],"msg":"Field required","input":{"type":"web_search_20250305","name":"web_search"}}]}, code: Unprocessable Entity, type: api_error

### Steps to Reproduce / 复现步骤

1. 创建 Anthropic 渠道
2. 在 codex 中使用

### Expected Behavior / 期望行为

原 0.9.x 版本使用时正常，升级 1.0 版本后报错，这可能是个回归 bug，期望 1.0 能和 0.9 版本一样正常使用。

### Error Message / 错误消息

```shell
failed to stream request: Request failed: Unprocessable Entity, error: {"detail":[{"type":"missing","loc":["body","tools",10,"input_schema"],"msg":"Field required","input":{"type":"web_search_20250305","name":"web_search"}}]}, code: Unprocessable Entity, type: api_error
```

### Operating System / 操作系统

Linux (Ubuntu/Debian) / Linux（Ubuntu/Debian）

### AxonHub Version / AxonHub 版本

v1.0.0-beta3

### Usage Scenario / 使用场景

Codex

### API Format / API 格式

Anthropic - Messages (/v1/messages) / Anthropic Messages, OpenAI - Responses (/v1/responses) / OpenAI Responses

### Channel Type / 渠道类型

Anthropic / Anthropic

### Logs / 日志

```shell

```

### Additional Context / 其他补充信息

_No response_

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

- When converting function-type tools for the Anthropic Messages API, the `input_schema` field was omitted entirely when a tool had nil or empty `Parameters`, due to `json:",omitempty"` on the field.
- Anthropic now requires `input_schema` to be present (even if empty) for all `function`-type tools; omitting it causes HTTP 422.
- This fix defaults `InputSchema` to `{"type":"object","properties":{}}` when `tool.Function.Parameters` is nil or zero-length.

## Why this matters

Fixes #1843. After upgrading to v1.0.0-beta3, any Anthropic channel request containing a function tool with no parameters (e.g. a client sending a `web_search` function tool without a parameter schema) fails with HTTP 422 from the Anthropic API because `input_schema` is missing. The canonical empty JSON Schema object satisfies Anthropic's validation for no-argument tools.

## Testing

- Added `TestConvertToolsAnthropic_NilParameters` in `outbound_convert_test.go` covering:
  - nil `Parameters` produces valid `{"type":"object","properties":{}}` as `InputSchema`
  - empty `Parameters` (`json.RawMessage{}`) gets the same default
  - explicit `Parameters` with a schema are passed through unchanged
- All 539 existing tests in the `anthropic` package continue to pass.
- `gofmt`, `go vet`, and `go build` clean.

Fixes #1843

### CODE REVIEW

**Comment by looplj** [comment]
https://platform.claude.com/docs/en/api/go/messages/create#web_search_tool_20260209

The web search tool is not function type, and no input schema field.

**Comment by mvanhorn** [comment]
Agreed that `web_search` is not a function type and must not carry an `input_schema`, and this PR keeps that invariant.

The default only fires inside the `case llm.ToolTypeFunction:` branch of `convertToolsAnthropic`:

```go
case llm.ToolTypeFunction:
    inputSchema := tool.Function.Parameters
    if len(inputSchema) == 0 {
        inputSchema = json.RawMessage(`{"type":"object","properties":{}}`)
    }
    // ...
case llm.ToolTypeWebSearch:
    // builds Tool{Type: ToolTypeWebSearch20250305, Name: ...} with no InputSchema
```

The `web_search` branch is untouched: it sets only `Type` and `Name`, and `InputSchema` keeps its `json:"input_schema,omitempty"` tag in `model.go`, so native tools serialize without an `input_schema` field. I intentionally did not take Greptile's suggestion to drop `omitempty`, for exactly this reason: removing it would force `input_schema: null` onto `web_search` and the other native tools.

So a no-arg function tool gets `{"type":"object","properties":{}}` and a `web_search` tool gets nothing, which I believe is the behavior you're describing.

If you're seeing a specific tool reaching the function branch when it shouldn't (e.g. a server-side tool arriving with `Type=function`), that would be a classification issue upstream of this conversion, and I'm happy to handle it separately if you can point me at the request shape that triggers it.
